#!/bin/bash

# environment directory
ENV_COLLECTION=~/dev/util/py-venv


switch_to_venv () {
    echo "switch to venv: $1"
    local DIR=$ENV_COLLECTION/$1 
    if [ ! -e $DIR ]; then
        echo "creating new venv..."
        python3 -m venv $DIR
    fi 
    source $DIR/bin/activate
}

# make sure directory for venv collection exists
if [ ! -e $ENV_COLLECTION ]; then
    mkdir -p $ENV_COLLECTION
    echo "creating dir ${ENV_COLLECTION}..." 
fi

if [ $# -gt 0 ]; then
    switch_to_venv $1
else
    OPTIONS=$(ls $ENV_COLLECTION)
    OPTIONS+=$'\n''deactivate'
    echo "options: ${OPTIONS}" 
    VENV=$(echo "${OPTIONS}" | fzf)
    #switch_to_venv $VENV
fi



